### ISSUE TITLE
Windows10 Windows11 系统下闪退

### ISSUE THREAD

**Issue by ZenY00u** [KangLin/TransformCoordinate#1]
Windows的event viewer显示

Faulting application name: TransformCoordinateApp.exe, version: 0.0.0.0, time stamp: 0x5dd66394
Faulting module name: RabbitCommon.dll, version: 0.0.0.0, time stamp: 0x5dd6638f
Exception code: 0xc0000094
Fault offset: 0x0001223b
Faulting process id: 0x256c
Faulting application start time: 0x01d992df746ffe31

**Comment by KangLin** [comment]
没有安装　ＶＣ　基础运行库。
在安装目录　bin 　下。运行　vcredist_x86.exe　安装　ＶＣ　基础运行库

**Comment by ZenY00u** [comment]
感谢！问题解决了！之前用的时候是没问题的，可能是windows更新，导致了这个问题的出现。重新装了这个运行库以后，问题得到了解决。
