### ISSUE TITLE
转换后的gpx文件中作者邮箱使用尖括号标签，会导致第三方无法解析

### ISSUE THREAD

**Issue by QingMings** [KangLin/TransformCoordinate#3]
软件非常好用，我用来转换gpx文件很有用。有一个小小的建议，如图中标红位置，邮箱用到了尖括号标签，我在第三方平台上传gpx时，会因为这个尖括号解析失败，需要打开文件重新编辑替换尖括号才行。希望作者大大可以考虑换下符号，再次感谢作者提供这么好的软件。
![image](https://github.com/user-attachments/assets/a1fef1b5-9c80-4826-a694-d51c411f55a7)

**Comment by KangLin** [comment]
谢谢你的建议。已修改。
